name: Update Contribution Activity Graph

on:
  schedule:
    - cron: "37 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: theme=tokyo-night&hide_border=true&area=true&radius=12&height=320&days=31&custom_title=Vedant%20Shinde%20-%20Contribution%20Activity
          output_path: profile/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated graph
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/activity-graph.svg
          git commit -m "Update contribution activity graph" || exit 0
          git push
